### ISSUE TITLE
Nba app checklist

### ISSUE THREAD

**Issue by pietroschoch** [pietroschoch/nba#1]
### Struture & Layout
- [ ] Define pages
- [ ] Define pages layout

### Development Struture
- [ ] Create react app
- [ ] Configure ESLint, Prettier & EditorConfig
- [ ] Create pages (routes)
